module APB_ms(input pCLK,pRESET,pWRITE_I,pTRANSFER,input [31:0]pWDATA,input [6:0]pADDR,input [3:0]pSTROBE,output pREADY,output [31:0]pRDATA_OUT,output  pSLAVE_ERROR_W);

wire pSELX,pENABLE,pWRITE,pSLAVE_ERROR;
wire [3:0] pSTROBE_I;
wire [31:0] pWDATA_I;
wire [6:0] pADDR_I;
//wire pSLAVE_ERROR_W;
wire [31:0]pRDATA;
Master APB_Master(pTRANSFER,pCLK,pRESET,pWRITE_I,pREADY,pSLAVE_ERROR,pSTROBE,pWDATA,pRDATA,pADDR,pSELX,pENABLE,pWRITE,pSLAVE_ERROR_W,pSTROBE_I,pWDATA_I,pRDATA_OUT,pADDR_I);
APB_slave slave(pCLK,pRESET,pSELX,pENABLE,pWRITE,pSTROBE_I,pWDATA_I,pADDR_I,pRDATA,pREADY,pSLAVE_ERROR);
endmodule
