//==================================================
// This file contains the Excluded objects
// Generated By User: rdonapat
// Format Version: 2
// Date: Thu Apr 24 10:00:04 2025
// ExclMode: default
//==================================================
CHECKSUM: "3843909181 235479103"
INSTANCE: apb_ms_tb.dut.APB_Master
Condition 4 "3345956107" "((pTRANSFER == 1'b0) && (pREADY == 1'b1)) 1 -1"
CHECKSUM: "1100724445 1935483864"
INSTANCE: apb_ms_tb.dut.slave
Condition 1 "1381502235" "((pSELX == 1'b1) && (pENABLE == 1'b0)) 1 -1"
Condition 4 "274187732" "((pSELX == 1'b1) && (pENABLE == 1'b1)) 1 -1"
Condition 7 "2092536644" "((pSELX == 1'b1) && (pENABLE == 1'b1)) 1 -1"
CHECKSUM: "1100724445 1564273864"
INSTANCE: apb_ms_tb.dut.slave
Branch 1 "869686693" "state" (3) "state SETUP ,-,0,-,-,-,-,-,-,-,-"
Branch 1 "869686693" "state" (14) "state default,-,-,-,-,-,-,-,-,-,-"
CHECKSUM: "1100724445 1514794641"
INSTANCE: apb_ms_tb.dut.slave
Block 10 "767136903" "next_state = IDLE;"
Block 30 "2067506889" "next_state = IDLE;"
